// <auto-generated />
namespace Tracing_Code_First.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addmigrationSqlInternalOps : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addmigrationSqlInternalOps));
        
        string IMigrationMetadata.Id
        {
            get { return "201212070649103_add-migration SqlInternalOps"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
